pluginBlacklist: ['local']
terminal:
  recoverTabs: false
enableAnalytics: false
enableWelcomeTab: false
delayOptionalPluginsForStartup: false
delayBackgroundTabRestoreForStartup: false
enableAutomaticUpdates: false
